// #include <assert.h>

#include <stdio.h>
#include <string.h>
#define NOB_IMPLEMENTATION
#include "./nob.h"

int getVersion(Nob_Cmd *cmd, Nob_String_Builder *hash) {
  int retVal = 1;
  nob_cmd_append(cmd, "/bin/sh", "-c",
                 "echo $(git describe --tags --exact-match 2>/dev/null"
                 "|| git rev-parse HEAD)"
                 " > ./build/commit");
  retVal = nob_cmd_run_sync(*cmd);
  cmd->count = 0;
  if (!retVal)
    return retVal;
  retVal = nob_read_entire_file("./build/commit", hash);
  return retVal;
}

int buildConfig(Nob_Cmd *cmd) {
  int result = 1;
  Nob_String_Builder hash = {0};
  FILE *fd = fopen("./build/config.h", "wb");
  if (fd == NULL) {
    nob_log(NOB_ERROR, "Failed to open build/config.h");
    nob_return_defer(0);
  }
  if (!getVersion(cmd, &hash)) {
    nob_log(NOB_ERROR, "Failed to get Version");
    nob_return_defer(0);
  }
  fputs("//This is a autogenerated file. Do not edit.\n", fd);
  fputs(nob_temp_sprintf("#define VERSION \"%s\"\n",
                         nob_temp_sv_to_cstr(nob_sv_trim(
                             nob_sv_from_parts(hash.items, hash.count)))),
        fd);
defer:
  nob_sb_free(hash);
  fclose(fd);
  return result;
}

int build_stash(Nob_Cmd *cmd) {
  int retVal = 1;
  if (!buildConfig(cmd)) {
    return 0;
  };
  nob_cmd_append(cmd, "cc");
  nob_cmd_append(cmd, "-Wall", "-Wextra", "-ggdb");
  nob_cmd_append(cmd, "-I.");
  nob_cmd_append(cmd, "-o", "./build/stash");
  nob_cmd_append(cmd, "./src/main.c");
  retVal = nob_cmd_run_sync(*cmd);
  cmd->count = 0;
  return retVal;
}

int run_stash(Nob_Cmd *cmd) {
  nob_log(NOB_INFO, "Running Stash");
  nob_cmd_append(cmd, "./build/stash");
  int retVal = nob_cmd_run_sync(*cmd);
  cmd->count = 0;
  return retVal;
}

void generate_build_folder() { nob_mkdir_if_not_exists("./build"); }

int main(int argc, char *argv[]) {
  NOB_GO_REBUILD_URSELF(argc, argv);
  int result = 0;
  const char *program = nob_shift_args(&argc, &argv);
  generate_build_folder();
  Nob_Cmd cmd = {0};
  if (!build_stash(&cmd)) {
    nob_log(NOB_ERROR, "Failed to build stash");
    nob_return_defer(EXIT_FAILURE);
  }

  if (argc <= 0) {
    nob_log(NOB_INFO, "Exiting");
    nob_return_defer(EXIT_SUCCESS);
  }
  const char *subcommand = nob_shift_args(&argc, &argv);
  nob_log(NOB_INFO, "%s", subcommand);
  if (strcmp(subcommand, "run") == 0) {
    run_stash(&cmd);
  }
defer:
  nob_cmd_free(cmd);
  return result;
}
